config/routes.rb
Rails.application.routes.draw do
 
  root 'pages#home'
  get 'home' => 'pages#home'
  get 'gen' => 'generator#gen'
  post 'gen' => 'generator#generate'
  get 'demandDistrib' => "pages#demandDistrib"
  #get 'generate' => 'generator#generatedData'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/generator.rb
require 'cs_demand'
require 'cs_station'
require 'generator_input'
require 'nokogiri'

class Generator

  include ActiveModel::Validations
					 
	attr_accessor :inputs, :list_stations, :list_demands
	
	validate do
	  @inputs.valid?
	end
	
	def initialize(gen_inputs)
	
		@inputs = gen_inputs

		@list_demands = Array.new
		@list_stations = Array.new
		@list_stations_insideCentroid = Array.new
		@list_stations_outsideCentroid = Array.new
		
		# induced parameters
		@areaLengthSide = @inputs.area_lenght_side
		@centroidAreaDimension = @inputs.centroid_area_dimension
		
		@sideOfTheCentroidArea = Integer(@areaLengthSide * Math.sqrt(@centroidAreaDimension.to_f/100))
		@minInCentroid = Integer(@areaLengthSide/2) - Integer(@sideOfTheCentroidArea/2)
		@maxInCentroid = Integer(@areaLengthSide/2) + Integer(@sideOfTheCentroidArea/2)

		@nbTSInOneDay = 1440 / @inputs.time_step
		@nbTSInOneHour = 60 / @inputs.time_step
		@demand = @inputs.demand
		@demandOverTimeCumulatedAndNormalised = init_demand
		@coefsTravelPenalty = init_coefsTravelPenalty
		
	end
	
	# Main generation method. Generates the random data (stations and demands)
	def generate_data
		generate_stations
		generate_demands
	end
	
	# Generate stations over the urban area
	def generate_stations
	
		case @inputs.generation_method
		when 'Centroïd'
	
			nbStationsInsideCentroid = Integer(@inputs.nb_stations * (@inputs.centroid_density.to_f / 100))
		
			(1..@inputs.nb_stations).each do |id|
			
				station = CS_station.new(id)
				
				station.insideCentroid = (id <= nbStationsInsideCentroid)
				station.maxSize = Random.rand(@inputs.parking_range_L..@inputs.parking_range_U)
		
				if(station.insideCentroid)
					station.xPos, station.yPos = generateCoords("inside")
					@list_stations_insideCentroid.push(station)
				else
					station.xPos, station.yPos = generateCoords("outside")
					@list_stations_outsideCentroid.push(station)
				end
				@list_stations.push(station)
				
			end
		when 'Uniform'
		else 
		end
	end
	
	# Generate demands over time among stations 
	def generate_demands
	
		case @inputs.generation_method
		when 'Centroïd'
		
			nbCreatedDemands = 1
			(1..@inputs.nb_demands).each do |idDemand|
				
				# Find a time
				rt = generate_random_time
				
				# Find 2 stations for that time
				station_O, station_D = pickTwoStations(rt)
				
				# Demand creation
				travelTime = calculate_TravelTime_TS(station_O, station_D, rt)
				arrivalTime = (rt + travelTime) % @nbTSInOneDay 
				
				demandAlreadyExists = false
				@list_demands.each do |d| # if the demand already exists, just increase its internal demand by 1
					if(d.sOrigin == station_O && d.sDestination == station_D && d.departureTime_TS == rt)
						d.increaseDemandBy(1)
						demandAlreadyExists = true
						break
					end
				end
				unless(demandAlreadyExists) # create a new demand if it does not exist
					@list_demands.push(CS_demand.new(nbCreatedDemands, station_O, station_D, rt, arrivalTime))
					nbCreatedDemands += 1
				end
			end
		
		when 'Uniform'
		else 
		end
	end
	
	
	# Initialize the coeficients for travel time penalties during rush hours
	def init_coefsTravelPenalty
		
		coefs = {}
		(0..(@nbTSInOneDay-1)).each do |ts|
			
			if is_in_period('morning', ts) || is_in_period('evening', ts)
				coefs[ts] = @inputs.time_penalty
			
			elsif is_in_period('outsideRushPeriods', ts)
				coefs[ts] = 1.0
			end
			
		end
		return coefs
	end
	
	
	# Calculate and return the travel time (in number of time-steps)
	# to go from 'station_O' to 'station_D' at 'timeDeparture'
	def calculate_TravelTime_TS(station_O, station_D, timeDeparture)
		
		travelTime_TS = 0
		time_TS = timeDeparture

		traveledDistance = 0.0
		totalDistance = calc_dist_between_stations(station_O, station_D)

		while (traveledDistance < totalDistance)
			traveledDistance += (@inputs.average_car_speed * 1000 / @nbTSInOneHour) * (1 / @coefsTravelPenalty[time_TS])
			time_TS = (time_TS + 1) % @nbTSInOneDay 
			travelTime_TS += 1
		end
		
		return travelTime_TS
	end
	
	
	# Pick and return two stations at the given time-step
	# 2 constraints of selection :
	# - rush period determines the orientation
	# - max distance ensures realistic demand
	def pickTwoStations(timeStep)
		
		station_O, station_D = nil, nil
		loop do
			if is_in_period('morning', timeStep)
				station_O = @list_stations_outsideCentroid.sample
				station_D = @list_stations_insideCentroid.sample
			
			elsif is_in_period('evening', timeStep)
				station_O = @list_stations_insideCentroid.sample
				station_D = @list_stations_outsideCentroid.sample
			
			elsif is_in_period('outsideRushPeriods', timeStep)
				list = @list_stations.sample(2)
				station_O = list[0]
				station_D = list[1]
			end

		  break unless calc_dist_between_stations(station_O, station_D) > @inputs.max_trip_distance
		end
		return station_O, station_D
	end
	
	
	# Return the distance (in meters) between the two stations
	def calc_dist_between_stations(stationOrigin, stationDestination)
		
		xO = Integer(stationOrigin.xPos)
		yO = Integer(stationOrigin.yPos)

		xD = Integer(stationDestination.xPos)
		yD = Integer(stationDestination.yPos)

		return Math.sqrt(((xD - xO)**2) + ((yD - yO)**2))
	end
	
	
	# Return true if 'timeStep' belongs to the given 'period' of the day
	# Possible values for 'period' are : 'morning', 'evening' and 'outsideRushPeriods'  
	def is_in_period(period, timeStep)
		
		mrts_l = convertHour2Ts(@inputs.morning_rush_time_slot_L)
		mrts_u = convertHour2Ts(@inputs.morning_rush_time_slot_U)
		erts_l = convertHour2Ts(@inputs.evening_rush_time_slot_L)
		erts_u = convertHour2Ts(@inputs.evening_rush_time_slot_U)
		
		case period
		when 'morning'
			return (mrts_l <= timeStep) && (timeStep <= mrts_u)
		when 'evening'
			return (erts_l <= timeStep) && (timeStep <= erts_u)
		when 'outsideRushPeriods'
			return 	(timeStep >= 0 && timeStep < mrts_l) ||     # before morning rush
					(timeStep > mrts_u && timeStep < erts_l) ||     # between morning and evening rushes
					(timeStep > erts_u && timeStep < @nbTSInOneDay) # after evening rush
		end
	end
	
	
	# Convert an hour into a number of time-steps
	def convertHour2Ts(hour)
		return Integer(((hour * 60 ) * @nbTSInOneDay) / 1440)
	end
	
	
	# Generate and return a pair of coordinates inside or outside the centroid area
	def generateCoords(position)
		case position
		when 'inside'
			xRandomValue = Random.rand(@minInCentroid..@maxInCentroid)
			yRandomValue = Random.rand(@minInCentroid..@maxInCentroid)
			return xRandomValue, yRandomValue
		when 'outside'
			xlist = [Random.rand(0..@minInCentroid), Random.rand(@maxInCentroid..@areaLengthSide)]
			ylist = [Random.rand(0..@minInCentroid), Random.rand(@maxInCentroid..@areaLengthSide)]
			return xlist.sample, ylist.sample
		end
	end
	
	# Generate and return the XML file corresponding to the generated data (stations and demands)
	def generate_xml
	
		builder = Nokogiri::XML::Builder.new do |xml|
  			xml.randomGeneratedData {
    			xml.parameters(nbStations: @inputs.nb_stations, nbDemands: @inputs.nb_demands)
          xml.stations {
            @list_stations.each do |s|
							xml.station(
								id: s.id, 
								xPos: s.xPos, 
								yPos: s.yPos,
								maxSize: s.maxSize
							)
            end
          }
  				xml.demands {
            @list_demands.each do |d|
  						xml.demand(
							  id: d.id,
								idsOrigin: d.sOrigin.id, 
								idsDestination: d.sDestination.id, 
								nbDemand: d.nbDemand,
								departureTime: d.departureTime_TS,
								arrivalTime: d.arrivalTime_TS
  						)
            end
  				}
  			}
		end
		
		return builder.to_xml
	end
	
	
	# Return the demand value at the time-step given in parameter
	def getDemandAt(timeStep)
		index = Integer(timeStep / @nbTSInOneHour)
		return @demand[index]
	end
	
	
	# Initialize the demand distribution as a cumulated and normalized distribution
	def init_demand
		
		# building the sum of the demand values
		sum_values = 0
		(0..(@nbTSInOneDay - 1)).each do |ts|
			sum_values += getDemandAt(ts)
		end
		
		# cululated sum + normalization 
		demand = {}
		(0..(@nbTSInOneDay - 1)).each do |ts|
			demand[ts] =
			if ts != 0
				demand[ts - 1] + (getDemandAt(ts).to_f / sum_values)
			else
				getDemandAt(ts).to_f / sum_values
			end
		end
		
		return demand
	end
	
	
	# Pick and return a random time generated from the demand distribution
	def generate_random_time
		random_value = Random.rand(0.0..1.0)
		(0..(@nbTSInOneDay - 1)).each do |ts|
			return ts if @demandOverTimeCumulatedAndNormalised[ts] >= random_value
		end
	end
	
end

app/controllers/generator_controller.rb
class GeneratorController < ApplicationController

	def generate
	
	  inputs = build_gen_inputs_from_form
	  
	  # Build the generator
		gen = Generator.new(inputs)
		
		# Validate inputs
		# TODO
		
		gen.generate_data
		@xml = gen.generate_xml
		
		#d = gen.getDemandTest
		
		#render plain: gen.nbStationsInsideCentroid.inspect
		
		render :xml => @xml
			#[
			#gen.stationList.inspect,
			#gen.minInCentroid.inspect,
			#gen.maxInCentroid.inspect,
			#gen.areaLengthSide.inspect,
			#@xml.inspect
			#]
		
		#render plain: gen.demandOverTimeCumulatedAndNormalised.inspect
		
		#render 'generatedData'
		#render plain: params[:gen]["nbStations"].inspect
	end
	
	# Returns inputs build from the form values
	def build_gen_inputs_from_form
    inputs = GeneratorInputBuilder.build do |builder|
      form = params[:gen]
	    builder.set_generation_method(form["generation_method"].to_s)
	    builder.set_nb_stations(form["nb_stations"].to_i)    
      builder.set_parking_ranges(form["parking_range_L"].to_i, form["parking_range_U"].to_i)
      builder.set_nb_demands(form["nb_demands"].to_i)
      builder.set_time_step(form["time_step"].to_i)
      builder.set_area_lenght_side(form["area_lenght_side"].to_i)
      builder.set_average_car_speed(form["average_car_speed"].to_i)
      builder.set_max_trip_distance(form["max_trip_distance"].to_i)
      builder.set_centroid_area_dimension(form["centroid_area_dimension"].to_i)
      builder.set_centroid_density(form["centroid_density"].to_i)
      
      mrtsl = form["morning_rush_time_slot_L"].to_i
      mrtsu = form["morning_rush_time_slot_U"].to_i
      mrdp = form["morning_rush_demand_proportion"].to_i
      builder.set_morning_rush_params(mrtsl, mrtsu, mrdp)
      
      ertsl = form["evening_rush_time_slot_L"].to_i
      ertsu = form["evening_rush_time_slot_U"].to_i
      erdp = form["evening_rush_demand_proportion"].to_i
      builder.set_evening_rush_params(ertsl, ertsu, erdp)
      
      builder.set_time_penalty(form["time_penalty"].to_i)
    
      demand = []
      (0..23).each do |h|
        demand[h] = form["demand_distrib_".concat(h.to_s)].to_i
      end
		  builder.set_demand(demand)
	  end
	  
	  inputs
	end

	def init
	end

end

app/helpers/generator_helper.rb
module GeneratorHelper
end

app/views/generator/gen.html.erb
<h1>Implémentation du générateur</h1>

<%= form_with scope: :gen, url: gen_path, local: true do |form| %>
	<p>Generation method: 
		<%= form.radio_button :generation_method, 'Centroïd', checked: true %>
		<%= label :generation_method, 'Centroïd' %>
		<%= form.radio_button :generation_method, 'Uniform' %>
		<%= label :generation_method, 'Uniform' %>
	</p>
	<p>Number of stations : <%= form.number_field :nb_stations, min: 1, step: 1, value: 10%></p>
	<p>Parking range (# parking slots): 
		<%= form.number_field :parking_range_L, min: 1, step: 1, value: 6 %>
		and
		<%= form.number_field :parking_range_U, min: 1, step: 1, value: 10 %>
	</p>
	<p>Number of demand (# requests): <%= form.number_field :nb_demands, min: 1, step: 1, value: 500 %></p>
	<p>Time step (min): <%= form.number_field :time_step, min: 1, max:60, step: 1, value: 10 %></p>
	<p>Area length side (m): <%= form.number_field :area_lenght_side, min: 1000, step: 1, value: 100000 %></p>
	<p>Average car speed (km/h): <%= form.number_field :average_car_speed, min: 1, step: 1, value: 40 %></p>
	<p>Maximum trip distance (m): <%= form.number_field :max_trip_distance, min: 1000, step: 1, value: 60000 %></p>
	<p>Centroïd area dimension (% of total area): <%= form.number_field :centroid_area_dimension, min: 1, step: 1, value: 10 %></p>
	<p>Density in the centroïd area (%): <%= form.number_field :centroid_density, in: 1..100, step: 1, value: 35 %></p>
	<p>Demand distribution :<br />
		<table>
			<tr>
				<% for i in 0..11 do %>
					<td><%=i%>h</td>
				<% end %>
			</tr>
			<tr>
				<td><%= form.number_field :demand_distrib_0, min: 0, max: 100, step: 1, value: 5 %></td>
				<td><%= form.number_field :demand_distrib_1, min: 0, max: 100, step: 1, value: 5 %></td>
				<td><%= form.number_field :demand_distrib_2, min: 0, max: 100, step: 1, value: 5 %></td>
				<td><%= form.number_field :demand_distrib_3, min: 0, max: 100, step: 1, value: 7 %></td>
				<td><%= form.number_field :demand_distrib_4, min: 0, max: 100, step: 1, value: 10 %></td>
				<td><%= form.number_field :demand_distrib_5, min: 0, max: 100, step: 1, value: 15 %></td>
				<td><%= form.number_field :demand_distrib_6, min: 0, max: 100, step: 1, value: 20 %></td>
				<td><%= form.number_field :demand_distrib_7, min: 0, max: 100, step: 1, value: 50 %></td>
				<td><%= form.number_field :demand_distrib_8, min: 0, max: 100, step: 1, value: 80 %></td>
				<td><%= form.number_field :demand_distrib_9, min: 0, max: 100, step: 1, value: 70 %></td>
				<td><%= form.number_field :demand_distrib_10, min: 0, max: 100, step: 1, value: 60 %></td>
				<td><%= form.number_field :demand_distrib_11, min: 0, max: 100, step: 1, value: 65 %></td>
			</tr>
			<tr>
				<% for i in 12..23 do %>
					<td><%=i%>h</td>
				<% end %>
			</tr>
			<tr>
				<td><%= form.number_field :demand_distrib_12, min: 0, max: 100, step: 1, value: 70 %></td>
				<td><%= form.number_field :demand_distrib_13, min: 0, max: 100, step: 1, value: 63 %></td>
				<td><%= form.number_field :demand_distrib_14, min: 0, max: 100, step: 1, value: 55 %></td>
				<td><%= form.number_field :demand_distrib_15, min: 0, max: 100, step: 1, value: 73 %></td>
				<td><%= form.number_field :demand_distrib_16, min: 0, max: 100, step: 1, value: 90 %></td>
				<td><%= form.number_field :demand_distrib_17, min: 0, max: 100, step: 1, value: 85 %></td>
				<td><%= form.number_field :demand_distrib_18, min: 0, max: 100, step: 1, value: 80 %></td>
				<td><%= form.number_field :demand_distrib_19, min: 0, max: 100, step: 1, value: 53 %></td>
				<td><%= form.number_field :demand_distrib_20, min: 0, max: 100, step: 1, value: 25 %></td>
				<td><%= form.number_field :demand_distrib_21, min: 0, max: 100, step: 1, value: 18 %></td>
				<td><%= form.number_field :demand_distrib_22, min: 0, max: 100, step: 1, value: 10 %></td>
				<td><%= form.number_field :demand_distrib_23, min: 0, max: 100, step: 1, value: 8 %></td>
			</tr>
		</table>
	</p>
	<p>Morning rush (sub -> center) time slot (h): 
		<%= form.number_field :morning_rush_time_slot_L, min: 1, step: 1, value: 7 %>
		and
		<%= form.number_field :morning_rush_time_slot_U, min: 1, step: 1, value: 9 %>
	</p>
	<p>Demand proportion during morning rush (%): <%= form.number_field :morning_rush_demand_proportion, in: 0..100, step: 1, value: 80 %></p>
	<p>Evening rush (center -> sub) time slot (h): 
		<%= form.number_field :evening_rush_time_slot_L, min: 12, step: 1, value: 15 %>
		and
		<%= form.number_field :evening_rush_time_slot_U, min: 12, step: 1, value: 19 %>
	</p>
	<p>Demand proportion during evening rush (%): <%= form.number_field :evening_rush_demand_proportion, in: 0..100, step: 1, value: 60 %></p>
	<p>Time penalty during rush hours (%): <%= form.number_field :time_penalty, min: 0, step: 1, value: 160 %></p>
	<p><%= form.submit "Generate!" %></p>
<% end %>